# Generated by Django 5.2.14 on 2026-05-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'completed')], default='pending', max_length=40)),
            ],
        ),
    ]
